alias vi='nvim'
alias gt='gnome-terminal'
alias jls='jupyter-lab --port=8889 --port-retries=0'
alias ll='ls -alF'
alias ls='ls -A'
alias l='ls -CF'
alias pair-tmux='tmux -S /tmp/sharedtmux new -s shared;chgrp pairprogrammers /tmp/sharedtmux'
alias share-tmux='tmux -S /tmp/sharedtmux attach -t new'
